#include "codegen.h"
#include <stdlib.h>
#include <string.h>
#include <stdio.h>
#include <stdarg.h>

codegen_t* codegen_create(void) {
    codegen_t* gen = (codegen_t*)malloc(sizeof(codegen_t));
    if (!gen) return NULL;
    
    gen->code = (char*)malloc(4096);
    gen->position = 0;
    gen->capacity = 4096;
    gen->indent_level = 0;
    
    return gen;
}

void codegen_free(codegen_t* gen) {
    if (gen) {
        if (gen->code) free(gen->code);
        free(gen);
    }
}

void codegen_emit(codegen_t* gen, const char* format, ...) {
    va_list args;
    va_start(args, format);
    
    int len = vsnprintf(NULL, 0, format, args);
    va_end(args);
    
    if (gen->position + len + 1 >= gen->capacity) {
        gen->capacity *= 2;
        gen->code = (char*)realloc(gen->code, gen->capacity);
    }
    
    va_start(args, format);
    vsnprintf(gen->code + gen->position, gen->capacity - gen->position, format, args);
    va_end(args);
    
    gen->position += len;
}

void codegen_emit_indent(codegen_t* gen) {
    for (int i = 0; i < gen->indent_level; i++) {
        codegen_emit(gen, "    ");
    }
}

void codegen_emit_newline(codegen_t* gen) {
    codegen_emit(gen, "\n");
}

void codegen_emit_string(codegen_t* gen, const char* str) {
    codegen_emit(gen, "%s", str);
}

char* codegen_generate(ast_node_t* ast) {
    codegen_t* gen = codegen_create();
    
    codegen_emit(gen, "// Generated by KenC# Compiler\n");
    codegen_emit(gen, "// KenuxOS Programming Language\n\n");
    
    codegen_generate_program(gen, ast);
    
    char* result = strdup(gen->code);
    codegen_free(gen);
    
    return result;
}

void codegen_generate_program(codegen_t* gen, ast_node_t* node) {
    for (int i = 0; i < node->child_count; i++) {
        ast_node_t* child = node->children[i];
        
        switch (child->type) {
            case AST_IMPORT_STMT:
                codegen_generate_import_stmt(gen, child);
                break;
            case AST_FUNCTION_DECL:
                codegen_generate_function_decl(gen, child);
                break;
            case AST_CLASS_DECL:
                codegen_generate_class_decl(gen, child);
                break;
            case AST_STRUCT_DECL:
                codegen_generate_struct_decl(gen, child);
                break;
            case AST_ENUM_DECL:
                codegen_generate_enum_decl(gen, child);
                break;
            default:
                break;
        }
    }
}

void codegen_generate_import_stmt(codegen_t* gen, ast_node_t* node) {
    codegen_emit(gen, "#include \"");
    if (node->child_count > 0 && node->children[0]->value) {
        codegen_emit(gen, "%s", node->children[0]->value);
    }
    codegen_emit(gen, ".h\"\n");
}

void codegen_generate_function_decl(codegen_t* gen, ast_node_t* node) {
    if (node->child_count > 0 && node->children[0]->value) {
        codegen_emit(gen, "%s ", node->children[0]->value);
    }
    
    if (node->child_count > 1 && node->children[1]->value) {
        codegen_emit(gen, "%s", node->children[1]->value);
    }
    
    codegen_emit(gen, "(");
    
    if (node->child_count > 2) {
        for (int i = 2; i < node->child_count; i++) {
            if (node->children[i]->type == AST_VARIABLE_DECL) {
                codegen_generate_variable_decl(gen, node->children[i]);
                if (i < node->child_count - 1) {
                    codegen_emit(gen, ", ");
                }
            }
        }
    }
    
    codegen_emit(gen, ")");
    
    if (node->child_count > 0) {
        for (int i = 0; i < node->child_count; i++) {
            if (node->children[i]->type == AST_BLOCK) {
                codegen_generate_block(gen, node->children[i]);
                return;
            }
        }
    }
    
    codegen_emit(gen, ";\n");
}

void codegen_generate_variable_decl(codegen_t* gen, ast_node_t* node) {
    if (node->child_count > 0 && node->children[0]->value) {
        codegen_emit(gen, "%s ", node->children[0]->value);
    }
    
    if (node->child_count > 1 && node->children[1]->value) {
        codegen_emit(gen, "%s", node->children[1]->value);
    }
    
    if (node->child_count > 2) {
        codegen_emit(gen, " = ");
        codegen_generate_expression(gen, node->children[2]);
    }
}

void codegen_generate_expression(codegen_t* gen, ast_node_t* node) {
    if (!node) return;
    
    switch (node->type) {
        case AST_LITERAL:
            codegen_generate_literal(gen, node);
            break;
        case AST_IDENTIFIER:
            codegen_generate_identifier(gen, node);
            break;
        case AST_BINARY_OP:
            codegen_generate_binary_op(gen, node);
            break;
        case AST_UNARY_OP:
            codegen_generate_unary_op(gen, node);
            break;
        case AST_FUNCTION_CALL:
            codegen_generate_function_call(gen, node);
            break;
        case AST_NEW_EXPR:
            codegen_generate_new_expr(gen, node);
            break;
        case AST_MEMBER_ACCESS:
            codegen_generate_member_access(gen, node);
            break;
        case AST_ARRAY_ACCESS:
            codegen_generate_array_access(gen, node);
            break;
        case AST_TERNARY_EXPR:
            codegen_generate_ternary_expr(gen, node);
            break;
        default:
            break;
    }
}

void codegen_generate_binary_op(codegen_t* gen, ast_node_t* node) {
    if (node->child_count >= 2) {
        codegen_emit(gen, "(");
        codegen_generate_expression(gen, node->children[0]);
        
        if (node->value) {
            codegen_emit(gen, " %s ", node->value);
        }
        
        codegen_generate_expression(gen, node->children[1]);
        codegen_emit(gen, ")");
    }
}

void codegen_generate_unary_op(codegen_t* gen, ast_node_t* node) {
    if (node->value) {
        codegen_emit(gen, "%s", node->value);
    }
    
    if (node->child_count > 0) {
        codegen_generate_expression(gen, node->children[0]);
    }
}

void codegen_generate_literal(codegen_t* gen, ast_node_t* node) {
    if (node->value) {
        codegen_emit(gen, "%s", node->value);
    }
}

void codegen_generate_identifier(codegen_t* gen, ast_node_t* node) {
    if (node->value) {
        codegen_emit(gen, "%s", node->value);
    }
}

void codegen_generate_function_call(codegen_t* gen, ast_node_t* node) {
    if (node->child_count > 0 && node->children[0]->value) {
        codegen_emit(gen, "%s(", node->children[0]->value);
    }
    
    for (int i = 1; i < node->child_count; i++) {
        codegen_generate_expression(gen, node->children[i]);
        if (i < node->child_count - 1) {
            codegen_emit(gen, ", ");
        }
    }
    
    codegen_emit(gen, ")");
}

void codegen_generate_if_statement(codegen_t* gen, ast_node_t* node) {
    codegen_emit_indent(gen);
    codegen_emit(gen, "if (");
    
    if (node->child_count > 0) {
        codegen_generate_expression(gen, node->children[0]);
    }
    
    codegen_emit(gen, ") ");
    
    if (node->child_count > 1) {
        if (node->children[1]->type == AST_BLOCK) {
            codegen_generate_block(gen, node->children[1]);
        } else {
            codegen_emit(gen, "{\n");
            gen->indent_level++;
            codegen_emit_indent(gen);
            codegen_generate_expression(gen, node->children[1]);
            codegen_emit(gen, ";\n");
            gen->indent_level--;
            codegen_emit_indent(gen);
            codegen_emit(gen, "}\n");
        }
    }
    
    if (node->child_count > 2) {
        codegen_emit_indent(gen);
        codegen_emit(gen, "else ");
        
        if (node->children[2]->type == AST_BLOCK) {
            codegen_generate_block(gen, node->children[2]);
        } else {
            codegen_emit(gen, "{\n");
            gen->indent_level++;
            codegen_emit_indent(gen);
            codegen_generate_expression(gen, node->children[2]);
            codegen_emit(gen, ";\n");
            gen->indent_level--;
            codegen_emit_indent(gen);
            codegen_emit(gen, "}\n");
        }
    }
}

void codegen_generate_while_statement(codegen_t* gen, ast_node_t* node) {
    codegen_emit_indent(gen);
    codegen_emit(gen, "while (");
    
    if (node->child_count > 0) {
        codegen_generate_expression(gen, node->children[0]);
    }
    
    codegen_emit(gen, ") ");
    
    if (node->child_count > 1) {
        codegen_generate_block(gen, node->children[1]);
    }
}

void codegen_generate_for_statement(codegen_t* gen, ast_node_t* node) {
    codegen_emit_indent(gen);
    codegen_emit(gen, "for (");
    
    if (node->child_count > 0) {
        codegen_generate_variable_decl(gen, node->children[0]);
    }
    
    codegen_emit(gen, "; ");
    
    if (node->child_count > 1) {
        codegen_generate_expression(gen, node->children[1]);
    }
    
    codegen_emit(gen, "; ");
    
    if (node->child_count > 2) {
        codegen_generate_expression(gen, node->children[2]);
    }
    
    codegen_emit(gen, ") ");
    
    if (node->child_count > 3) {
        codegen_generate_block(gen, node->children[3]);
    }
}

void codegen_generate_return_statement(codegen_t* gen, ast_node_t* node) {
    codegen_emit_indent(gen);
    codegen_emit(gen, "return");
    
    if (node->child_count > 0) {
        codegen_emit(gen, " ");
        codegen_generate_expression(gen, node->children[0]);
    }
    
    codegen_emit(gen, ";\n");
}

void codegen_generate_block(codegen_t* gen, ast_node_t* node) {
    codegen_emit_indent(gen);
    codegen_emit(gen, "{\n");
    gen->indent_level++;
    
    for (int i = 0; i < node->child_count; i++) {
        ast_node_t* child = node->children[i];
        
        switch (child->type) {
            case AST_VARIABLE_DECL:
                codegen_emit_indent(gen);
                codegen_generate_variable_decl(gen, child);
                codegen_emit(gen, ";\n");
                break;
            case AST_IF_STATEMENT:
                codegen_generate_if_statement(gen, child);
                break;
            case AST_WHILE_STATEMENT:
                codegen_generate_while_statement(gen, child);
                break;
            case AST_FOR_STATEMENT:
                codegen_generate_for_statement(gen, child);
                break;
            case AST_RETURN_STATEMENT:
                codegen_generate_return_statement(gen, child);
                break;
            case AST_TRY_CATCH:
                codegen_generate_try_catch(gen, child);
                break;
            case AST_THROW_STMT:
                codegen_generate_throw_stmt(gen, child);
                break;
            default:
                codegen_emit_indent(gen);
                codegen_generate_expression(gen, child);
                codegen_emit(gen, ";\n");
                break;
        }
    }
    
    gen->indent_level--;
    codegen_emit_indent(gen);
    codegen_emit(gen, "}\n");
}

void codegen_generate_class_decl(codegen_t* gen, ast_node_t* node) {
    codegen_emit(gen, "typedef struct %s %s;\n\n", node->children[0]->value, node->children[0]->value);
    codegen_emit(gen, "struct %s {\n", node->children[0]->value);
    gen->indent_level++;
    
    for (int i = 1; i < node->child_count; i++) {
        ast_node_t* child = node->children[i];
        
        if (child->type == AST_PROPERTY_DECL) {
            codegen_emit_indent(gen);
            codegen_generate_property_decl(gen, child);
            codegen_emit(gen, ";\n");
        } else if (child->type == AST_METHOD_DECL) {
            codegen_emit_indent(gen);
            codegen_emit(gen, "// Method: ");
            if (child->child_count > 1 && child->children[1]->value) {
                codegen_emit(gen, "%s\n", child->children[1]->value);
            }
        }
    }
    
    gen->indent_level--;
    codegen_emit(gen, "};\n\n");
    
    for (int i = 1; i < node->child_count; i++) {
        if (node->children[i]->type == AST_METHOD_DECL) {
            codegen_generate_method_decl(gen, node->children[i], node->children[0]->value);
        }
    }
}

void codegen_generate_method_decl(codegen_t* gen, ast_node_t* node, const char* class_name) {
    if (node->child_count > 0 && node->children[0]->value) {
        codegen_emit(gen, "%s ", node->children[0]->value);
    }
    
    codegen_emit(gen, "%s_%s(", class_name, node->children[1]->value);
    codegen_emit(gen, "%s* this", class_name);
    
    for (int i = 2; i < node->child_count; i++) {
        if (node->children[i]->type == AST_VARIABLE_DECL) {
            codegen_emit(gen, ", ");
            codegen_generate_variable_decl(gen, node->children[i]);
        }
    }
    
    codegen_emit(gen, ")");
    
    for (int i = 0; i < node->child_count; i++) {
        if (node->children[i]->type == AST_BLOCK) {
            codegen_generate_block(gen, node->children[i]);
            return;
        }
    }
    
    codegen_emit(gen, ";\n");
}

void codegen_generate_property_decl(codegen_t* gen, ast_node_t* node) {
    if (node->child_count > 0 && node->children[0]->value) {
        codegen_emit(gen, "%s ", node->children[0]->value);
    }
    
    if (node->child_count > 1 && node->children[1]->value) {
        codegen_emit(gen, "%s", node->children[1]->value);
    }
}

void codegen_generate_new_expr(codegen_t* gen, ast_node_t* node) {
    codegen_emit(gen, "malloc(sizeof(");
    
    if (node->child_count > 0 && node->children[0]->value) {
        codegen_emit(gen, "%s", node->children[0]->value);
    }
    
    codegen_emit(gen, "))");
}

void codegen_generate_member_access(codegen_t* gen, ast_node_t* node) {
    if (node->child_count > 0) {
        codegen_generate_expression(gen, node->children[0]);
    }
    
    if (node->value) {
        codegen_emit(gen, "%s", node->value);
    }
    
    if (node->child_count > 1 && node->children[1]->value) {
        codegen_emit(gen, "%s", node->children[1]->value);
    }
}

void codegen_generate_array_access(codegen_t* gen, ast_node_t* node) {
    if (node->child_count > 0) {
        codegen_generate_expression(gen, node->children[0]);
    }
    
    codegen_emit(gen, "[");
    
    if (node->child_count > 1) {
        codegen_generate_expression(gen, node->children[1]);
    }
    
    codegen_emit(gen, "]");
}

void codegen_generate_try_catch(codegen_t* gen, ast_node_t* node) {
    codegen_emit_indent(gen);
    codegen_emit(gen, "try ");
    
    if (node->child_count > 0) {
        codegen_generate_block(gen, node->children[0]);
    }
    
    if (node->child_count > 1) {
        codegen_emit_indent(gen);
        codegen_emit(gen, "catch (");
        
        if (node->children[1]->child_count > 0) {
            codegen_generate_variable_decl(gen, node->children[1]->children[0]);
        }
        
        codegen_emit(gen, ") ");
        
        if (node->children[1]->child_count > 1) {
            codegen_generate_block(gen, node->children[1]->children[1]);
        }
    }
    
    if (node->child_count > 2) {
        codegen_emit_indent(gen);
        codegen_emit(gen, "finally ");
        
        if (node->children[2]->type == AST_BLOCK) {
            codegen_generate_block(gen, node->children[2]);
        }
    }
}

void codegen_generate_throw_stmt(codegen_t* gen, ast_node_t* node) {
    codegen_emit_indent(gen);
    codegen_emit(gen, "throw ");
    
    if (node->child_count > 0) {
        codegen_generate_expression(gen, node->children[0]);
    }
    
    codegen_emit(gen, ";\n");
}

void codegen_generate_struct_decl(codegen_t* gen, ast_node_t* node) {
    codegen_emit(gen, "typedef struct %s %s;\n\n", node->children[0]->value, node->children[0]->value);
    codegen_emit(gen, "struct %s {\n", node->children[0]->value);
    gen->indent_level++;
    
    for (int i = 1; i < node->child_count; i++) {
        if (node->children[i]->type == AST_VARIABLE_DECL) {
            codegen_emit_indent(gen);
            codegen_generate_variable_decl(gen, node->children[i]);
            codegen_emit(gen, ";\n");
        }
    }
    
    gen->indent_level--;
    codegen_emit(gen, "};\n\n");
}

void codegen_generate_enum_decl(codegen_t* gen, ast_node_t* node) {
    codegen_emit(gen, "typedef enum {\n");
    gen->indent_level++;
    
    for (int i = 1; i < node->child_count; i++) {
        codegen_emit_indent(gen);
        
        if (node->children[i]->value) {
            codegen_emit(gen, "%s", node->children[i]->value);
        }
        
        if (i < node->child_count - 1) {
            codegen_emit(gen, ",");
        }
        
        codegen_emit(gen, "\n");
    }
    
    gen->indent_level--;
    codegen_emit(gen, "} %s;\n\n", node->children[0]->value);
}

void codegen_generate_ternary_expr(codegen_t* gen, ast_node_t* node) {
    if (node->child_count >= 3) {
        codegen_emit(gen, "(");
        codegen_generate_expression(gen, node->children[0]);
        codegen_emit(gen, ") ? (");
        codegen_generate_expression(gen, node->children[1]);
        codegen_emit(gen, ") : (");
        codegen_generate_expression(gen, node->children[2]);
        codegen_emit(gen, ")");
    }
}